const fs = require('fs');
const path = require('path');
const zlib = require('zlib');
const { escapeHtml } = require('./utils');

function generate(stats, synthesis, outputPath) {
  // 1. Pre-calculate userResponseTimes histogram in the generator
  const bins = { "2-10s": 0, "10-30s": 0, "30s-1m": 0, "1-2m": 0, "2-5m": 0, "5-15m": 0, ">15m": 0 };
  if (stats.userResponseTimes) {
    for (const t of stats.userResponseTimes) {
      if (t < 10) bins["2-10s"]++;
      else if (t < 30) bins["10-30s"]++;
      else if (t < 60) bins["30s-1m"]++;
      else if (t < 120) bins["1-2m"]++;
      else if (t < 300) bins["2-5m"]++;
      else if (t < 900) bins["5-15m"]++;
      else bins[">15m"]++;
    }
  }

  // 2. Data Capping & Cleaning
  const cleanStats = {
    tm: stats.totalMessages || 0,
    sa: stats.sessionsAnalyzed || 0,
    la: stats.linesAdded || 0,
    lr: stats.linesRemoved || 0,
    ft: stats.filesTouchedCount || 0,
    ad: stats.activeDays || 0,
    to: Object.fromEntries(Object.entries(stats.tools || {}).sort((a,b) => b[1]-a[1]).slice(0, 8)),
    lg: Object.fromEntries(Object.entries(stats.languages || {}).sort((a,b) => b[1]-a[1]).slice(0, 8)),
    er: Object.fromEntries(Object.entries(stats.toolErrors || {}).sort((a,b) => b[1]-a[1]).slice(0, 6)),
    ha: stats.hourlyActivity || [],
    rt: bins,
    mrt: stats.median_response_time || 0,
    art: stats.avg_response_time || 0,
    mc: stats.multi_clauding || {},
    dr: stats.dateRange || {},
    ql: stats.qualitative || {}
  };

  if (stats.meta) {
    cleanStats.me = {
      qs: stats.meta.qualitativeSessionsAnalyzed,
      gt: stats.meta.generationTimeMs
    };
  }

  // 3. Synthesis Minification
  const minSy = {
    ag: synthesis.at_a_glance || {},
    pa: (synthesis.project_areas || []).slice(0, 5),
    is: synthesis.interaction_style || {},
    ww: synthesis.what_works || {},
    fa: synthesis.friction_analysis || {},
    su: synthesis.suggestions || {},
    oh: synthesis.on_the_horizon || {},
    fm: synthesis.fun_moment
  };

  const embeddedData = { s: cleanStats, y: minSy };
  const jsonData = JSON.stringify(embeddedData);
  const compressed = zlib.gzipSync(jsonData);
  const base64Data = compressed.toString('base64');

  const htmlParts = [
    '<!DOCTYPE html>',
    '<html>',
    '<head>',
    '  <meta charset="utf-8">',
    '  <meta name="viewport" content="width=device-width, initial-scale=1.0">',
    '  <title>Gemini CLI Insights</title>',
    '  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">',
    '  <style>',
    '    * { box-sizing: border-box; margin: 0; padding: 0; }',
    '    body { font-family: "Inter", -apple-system, BlinkMacSystemFont, sans-serif; background: #f8fafc; color: #334155; line-height: 1.65; padding: 48px 24px; }',
    '    .container { max-width: 800px; margin: 0 auto; }',
    '    .header-row { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 8px; flex-wrap: wrap; gap: 16px; }',
    '    h1 { font-size: 32px; font-weight: 700; color: #0f172a; }',
    '    .share-btn { background: #6366f1; color: white; border: none; border-radius: 6px; padding: 8px 16px; font-size: 14px; font-weight: 600; cursor: pointer; transition: background 0.2s; display: flex; align-items: center; gap: 8px; }',
    '    .share-btn:hover { background: #4f46e5; }',
    '    h2 { font-size: 20px; font-weight: 600; color: #0f172a; margin-top: 48px; margin-bottom: 16px; }',
    '    .subtitle { color: #64748b; font-size: 15px; margin-bottom: 32px; }',
    '    .nav-toc { display: flex; flex-wrap: wrap; gap: 8px; margin: 24px 0 32px 0; padding: 16px; background: white; border-radius: 8px; border: 1px solid #e2e8f0; }',
    '    .nav-toc a { font-size: 12px; color: #64748b; text-decoration: none; padding: 6px 12px; border-radius: 6px; background: #f1f5f9; transition: all 0.15s; }',
    '    .nav-toc a:hover { background: #e2e8f0; color: #334155; }',
    '    .stats-row { display: flex; gap: 24px; margin-bottom: 40px; padding: 20px 0; border-top: 1px solid #e2e8f0; border-bottom: 1px solid #e2e8f0; flex-wrap: wrap; }',
    '    .stat { text-align: center; }',
    '    .stat-value { font-size: 24px; font-weight: 700; color: #0f172a; }',
    '    .stat-label { font-size: 11px; color: #64748b; text-transform: uppercase; }',
    '    .at-a-glance { background: linear-gradient(135deg, #fef3c7 0%, #fde68a 100%); border: 1px solid #f59e0b; border-radius: 12px; padding: 20px 24px; margin-bottom: 32px; }',
    '    .glance-title { font-size: 16px; font-weight: 700; color: #92400e; margin-bottom: 16px; }',
    '    .glance-sections { display: flex; flex-direction: column; gap: 12px; }',
    '    .glance-section { font-size: 14px; color: #78350f; line-height: 1.6; }',
    '    .glance-section strong { color: #92400e; }',
    '    .project-areas { display: flex; flex-direction: column; gap: 12px; margin-bottom: 32px; }',
    '    .project-area { background: white; border: 1px solid #e2e8f0; border-radius: 8px; padding: 16px; }',
    '    .area-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 8px; }',
    '    .area-name { font-weight: 600; font-size: 15px; color: #0f172a; }',
    '    .area-count { font-size: 12px; color: #64748b; background: #f1f5f9; padding: 2px 8px; border-radius: 4px; }',
    '    .area-desc { font-size: 14px; color: #475569; line-height: 1.5; }',
    '    .narrative { background: white; border: 1px solid #e2e8f0; border-radius: 8px; padding: 20px; margin-bottom: 24px; }',
    '    .narrative p { margin-bottom: 12px; font-size: 14px; color: #475569; line-height: 1.7; }',
    '    .key-insight { background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 8px; padding: 12px 16px; margin-top: 12px; font-size: 14px; color: #166534; }',
    '    .big-wins { display: flex; flex-direction: column; gap: 12px; margin-bottom: 24px; }',
    '    .big-win { background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 8px; padding: 16px; }',
    '    .big-win-title { font-weight: 600; font-size: 15px; color: #166534; margin-bottom: 8px; }',
    '    .big-win-desc { font-size: 14px; color: #15803d; line-height: 1.5; }',
    '    .friction-categories { display: flex; flex-direction: column; gap: 16px; margin-bottom: 24px; }',
    '    .friction-category { background: #fef2f2; border: 1px solid #fca5a5; border-radius: 8px; padding: 16px; }',
    '    .friction-title { font-weight: 600; font-size: 15px; color: #991b1b; margin-bottom: 6px; }',
    '    .friction-desc { font-size: 13px; color: #7f1d1d; margin-bottom: 10px; }',
    '    .friction-examples { margin: 0 0 0 20px; font-size: 13px; color: #334155; }',
    '    .friction-examples li { margin-bottom: 4px; }',
    '    .claude-md-section { background: #eff6ff; border: 1px solid #bfdbfe; border-radius: 8px; padding: 16px; margin-bottom: 20px; }',
    '    .claude-md-section h3 { font-size: 14px; font-weight: 600; color: #1e40af; margin: 0 0 12px 0; }',
    '    .claude-md-item { display: flex; flex-wrap: wrap; align-items: flex-start; gap: 8px; padding: 10px 0; border-bottom: 1px solid #dbeafe; }',
    '    .claude-md-item:last-child { border-bottom: none; }',
    '    .cmd-code { background: white; padding: 8px 12px; border-radius: 4px; font-size: 12px; color: #1e40af; border: 1px solid #bfdbfe; font-family: monospace; display: block; white-space: pre-wrap; word-break: break-word; flex: 1; }',
    '    .cmd-why { font-size: 12px; color: #64748b; width: 100%; padding-left: 24px; margin-top: 4px; }',
    '    .charts-row { display: grid; grid-template-columns: 1fr 1fr; gap: 24px; margin: 24px 0; }',
    '    .chart-card { background: white; border: 1px solid #e2e8f0; border-radius: 8px; padding: 16px; }',
    '    .chart-title { font-size: 12px; font-weight: 600; color: #64748b; text-transform: uppercase; margin-bottom: 12px; }',
    '    .bar-row { display: flex; align-items: center; margin-bottom: 6px; }',
    '    .bar-label { width: 100px; font-size: 11px; color: #475569; flex-shrink: 0; position: relative; }',
    '    .bar-track { flex: 1; height: 6px; background: #f1f5f9; border-radius: 3px; margin: 0 8px; }',
    '    .bar-fill { height: 100%; border-radius: 3px; }',
    '    .bar-value { width: 28px; font-size: 11px; font-weight: 500; color: #64748b; text-align: right; }',
    '    .tooltip { cursor: help; border-bottom: 1px dotted #94a3b8; display: inline-block; max-width: 100%; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }',
    '    .tooltip:hover { overflow: visible; }',
    '    .tooltip:hover::after {',
    '      content: attr(data-tip);',
    '      position: absolute;',
    '      bottom: 100%;',
    '      left: 0;',
    '      background: #1e293b;',
    '      color: white;',
    '      padding: 8px 12px;',
    '      border-radius: 6px;',
    '      font-size: 12px;',
    '      white-space: normal;',
    '      width: 220px;',
    '      z-index: 1000;',
    '      line-height: 1.4;',
    '      font-weight: 400;',
    '      text-transform: none;',
    '      box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1);',
    '      margin-bottom: 8px;',
    '    }',
    '    .tooltip:hover::before {',
    '      content: "";',
    '      position: absolute;',
    '      bottom: 100%;',
    '      left: 10px;',
    '      border: 6px solid transparent;',
    '      border-top-color: #1e293b;',
    '      z-index: 1000;',
    '      margin-bottom: -4px;',
    '    }',
    '    .meta-stats { border-top: 1px solid #e2e8f0; margin-top: 48px; padding-top: 16px; font-size: 12px; color: #94a3b8; display: flex; justify-content: space-between; }',
    '    .copy-btn { background: #e2e8f0; border: none; border-radius: 4px; padding: 4px 8px; font-size: 11px; cursor: pointer; color: #475569; }',
    '    .feature-card, .pattern-card, .horizon-card { background: white; border: 1px solid #e2e8f0; border-radius: 8px; padding: 16px; margin-bottom: 12px; }',
    '    .example-code, .copyable-prompt { background: #f1f5f9; padding: 8px 12px; border-radius: 4px; font-family: monospace; font-size: 12px; display: block; white-space: pre-wrap; margin-bottom: 8px; }',
    '    .fun-ending { background: linear-gradient(135deg, #fef3c7 0%, #fde68a 100%); border: 1px solid #fbbf24; border-radius: 12px; padding: 24px; margin-top: 40px; text-align: center; }',
    '    .fun-headline { font-size: 18px; font-weight: 600; color: #78350f; margin-bottom: 8px; }',
    '    .fun-detail { font-size: 14px; color: #92400e; }',
    '    .loader-overlay { position: fixed; inset: 0; background: white; display: flex; align-items: center; justify-content: center; z-index: 1000; }',
    '    .loader-text { font-size: 18px; font-weight: 600; color: #6366f1; animation: pulse 1.5s infinite; }',
    '    @keyframes pulse { 0%, 100% { opacity: 1; } 50% { opacity: 0.5; } }',
    '    @media (max-width: 640px) { .charts-row { grid-template-columns: 1fr; } }',
    '  </style>',
    '</head>',
    '<body>',
    '  <div id="loader" class="loader-overlay"><div class="loader-text">Loading Insights...</div></div>',
    '  <div id="root" class="container" style="display: none;"></div>',
    '  <script>',
    '    const EMBEDDED_DATA = "' + base64Data + '";',
    '    const DESCRIPTIONS = {',
    '      "fully_achieved": "The user\'s goal was completely met.",',
    '      "mostly_achieved": "The user\'s main goal was met, with minor items left or small issues.",',
    '      "partially_achieved": "Some progress was made, but the main goal wasn\'t fully reached.",',
    '      "not_achieved": "No significant progress toward the user\'s goal.",',
    '      "unclear_from_transcript": "The transcript ended before the outcome was certain.",',
    '      "none": "No specific success factor stood out.",',
    '      "fast_accurate_search": "Finding the right files or information quickly.",',
    '      "correct_code_edits": "Writing code that worked as expected on the first or second try.",',
    '      "good_explanations": "Providing clear, educational, or helpful context.",',
    '      "proactive_help": "Suggesting better ways or identifying issues before they occurred.",',
    '      "multi_file_changes": "Orchestrating complex changes across several files reliably.",',
    '      "good_debugging": "Identifying and fixing bugs efficiently.",',
    '      "unhelpful": "Did not contribute to the goal or made things harder.",',
    '      "slightly_helpful": "Minimal contribution, perhaps just minor tasks.",',
    '      "moderately_helpful": "Provided solid assistance but required significant guidance.",',
    '      "very_helpful": "Significantly accelerated the work with minimal friction.",',
    '      "essential": "The task would have been much harder or impossible without Gemini CLI."',
    '    };',
    '    ',
    '    async function decompress(base64) {',
    '      try {',
    '        const bytes = Uint8Array.from(atob(base64), c => c.charCodeAt(0));',
    '        const ds = new DecompressionStream("gzip");',
    '        const stream = new ReadableStream({',
    '          start(controller) { controller.enqueue(bytes); controller.close(); }',
    '        }).pipeThrough(ds);',
    '        const response = new Response(stream);',
    '        const text = await response.text();',
    '        const data = JSON.parse(text);',
    '        if (data.s && data.y) {',
    '          return {',
    '            stats: {',
    '              totalMessages: data.s.tm,',
    '              sessionsAnalyzed: data.s.sa,',
    '              linesAdded: data.s.la,',
    '              linesRemoved: data.s.lr,',
    '              filesTouchedCount: data.s.ft,',
    '              activeDays: data.s.ad,',
    '              tools: data.s.to,',
    '              languages: data.s.lg,',
    '              toolErrors: data.s.er,',
    '              hourlyActivity: data.s.ha,',
    '              userResponseTimesBins: data.s.rt,',
    '              median_response_time: data.s.mrt,',
    '              avg_response_time: data.s.art,',
    '              multi_clauding: data.s.mc,',
    '              dateRange: data.s.dr,',
    '              qualitative: data.s.ql,',
    '              meta: data.s.me ? { qualitativeSessionsAnalyzed: data.s.me.qs, generationTimeMs: data.s.me.gt } : null',
    '            },',
    '            synthesis: {',
    '              at_a_glance: data.y.ag,',
    '              project_areas: data.y.pa,',
    '              interaction_style: data.y.is,',
    '              what_works: data.y.ww,',
    '              friction_analysis: data.y.fa,',
    '              suggestions: data.y.su,',
    '              on_the_horizon: data.y.oh,',
    '              fun_moment: data.y.fm',
    '            }',
    '          };',
    '        }',
    '        return data;',
    '      } catch (e) {',
    '        console.error("Decompression failed", e);',
    '        return null;',
    '      }',
    '    }',
    '',
    '    function escapeHtml(unsafe) {',
    '      if (!unsafe) return "";',
    '      return unsafe.toString().replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/\\\'/g, "&#039;");',
    '    }',
    '',
    '    function copyText(text, btn) {',
    '      navigator.clipboard.writeText(text).then(() => {',
    '        const oldText = btn.textContent;',
    '        btn.textContent = "Copied!";',
    '        setTimeout(() => { btn.textContent = oldText; }, 2000);',
    '      });',
    '    }',
    '',
    '    function shareInsights(btn) {',
    '      const urlParams = new URLSearchParams(window.location.search);',
    '      const hashData = window.location.hash.startsWith("#data=") ? window.location.hash.substring(6) : null;',
    '      const dataString = urlParams.get("data") || hashData || EMBEDDED_DATA;',
    '      ',
    '      const url = new URL(window.location.href);',
    '      url.search = "";',
    '      url.hash = "data=" + dataString;',
    '      navigator.clipboard.writeText(url.toString()).then(() => {',
    '        const oldText = btn.innerHTML;',
    '        btn.innerHTML = "Link Copied!";',
    '        setTimeout(() => { btn.innerHTML = oldText; }, 2000);',
    '      });',
    '    }',
    '',
    '    function renderBarChart(data, color, limit = 6) {',
    '      if (!data) return "<p class=\'empty\'>No data</p>";',
    '      const entries = Object.entries(data).sort((a, b) => b[1] - a[1]).slice(0, limit);',
    '      if (entries.length === 0) return "<p class=\'empty\'>No data</p>";',
    '      const max = Math.max(...entries.map(e => e[1]));',
    '      return entries.map(([label, val]) => {',
    '        const width = max > 0 ? (val / max) * 100 : 0;',
    '        const desc = DESCRIPTIONS[label];',
    '        const labelHtml = desc ? `<span class="tooltip" data-tip="${escapeHtml(desc)}">${escapeHtml(label)}</span>` : escapeHtml(label);',
    '        return `<div class="bar-row">',
    '            <div class="bar-label">${labelHtml}</div>',
    '            <div class="bar-track"><div class="bar-fill" style="width:${width}%;background:${color}"></div></div>',
    '            <div class="bar-value">${val}</div>',
    '          </div>`;',
    '      }).join("");',
    '    }',
    '',
    '    function renderResponseTimes(bins) {',
    '      if (!bins) return "<p class=\'empty\'>No data</p>";',
    '      const max = Math.max(...Object.values(bins));',
    '      return Object.entries(bins).map(([label, val]) => {',
    '        const width = max > 0 ? (val / max) * 100 : 0;',
    '        return `<div class="bar-row">',
    '            <div class="bar-label">${label}</div>',
    '            <div class="bar-track"><div class="bar-fill" style="width:${width}%;background:#6366f1"></div></div>',
    '            <div class="bar-value">${val}</div>',
    '          </div>`;',
    '      }).join("");',
    '    }',
    '',
    '    async function renderApp() {',
    '      const urlParams = new URLSearchParams(window.location.search);',
    '      const hashData = window.location.hash.startsWith("#data=") ? window.location.hash.substring(6) : null;',
    '      const dataString = urlParams.get("data") || hashData || EMBEDDED_DATA;',
    '      ',
    '      const data = await decompress(dataString);',
    '      if (!data) {',
    '        document.getElementById("loader").innerHTML = \'<div class="loader-text" style="color:#ef4444">Failed to load data</div>\';',
    '        return;',
    '      }',
    '',
    '      const { stats, synthesis } = data;',
    '      const root = document.getElementById("root");',
    '      const formatMarkdown = (str) => {',
    '        if (!str) return "";',
    '        return str.replace(/\\*\\*(.+?)\\*\\*/g, "<strong>$1</strong>");',
    '      };',
    '',
    '      root.innerHTML = `',
    '        <div class="header-row">',
    '          <h1>Gemini CLI Insights</h1>',
    '          <button class="share-btn" onclick="shareInsights(this)">',
    '            <svg width="16" height="16" fill="currentColor" viewBox="0 0 24 24"><path d="M18 16.08c-.76 0-1.44.3-1.96.77L8.91 12.7c.05-.23.09-.46.09-.7s-.04-.47-.09-.7l7.05-4.11c.54.5 1.25.81 2.04.81 1.66 0 3-1.34 3-3s-1.34-3-3-3-3 1.34-3 3c0 .24.04.47.09.7L8.04 9.81C7.5 9.31 6.79 9 6 9c-1.66 0-3 1.34-3 3s1.34 3 3 3c.79 0 1.5-.31 2.04-.81l7.12 4.16c-.05.21-.08.43-.08.65 0 1.61 1.31 2.92 2.92 2.92 1.61 0 2.92-1.31 2.92-2.92s-1.31-2.92-2.92-2.92z"/></svg>',
    '            Share Your Insights',
    '          </button>',
    '        </div>',
    '        <p class="subtitle">',
    '          ${(stats.totalMessages || 0).toLocaleString()} messages across ${stats.sessionsAnalyzed || 0} sessions',
    '          ${stats.meta ? `<br>Qualitative Deep-Dives on ${stats.meta.qualitativeSessionsAnalyzed} sessions` : ""}',
    '          | ${stats.dateRange?.start || ""} to ${stats.dateRange?.end || ""}',
    '        </p>',
    '',
    '        <div class="at-a-glance">',
    '          <div class="glance-title">At a Glance</div>',
    '          <div class="glance-sections">',
    '            <div class="glance-section"><strong>What\'s working:</strong> ${formatMarkdown(escapeHtml(synthesis.at_a_glance?.whats_working || ""))}</div>',
    '            <div class="glance-section"><strong>What\'s hindering:</strong> ${formatMarkdown(escapeHtml(synthesis.at_a_glance?.whats_hindering || ""))}</div>',
    '            <div class="glance-section"><strong>Quick wins:</strong> ${formatMarkdown(escapeHtml(synthesis.at_a_glance?.quick_wins || ""))}</div>',
    '            <div class="glance-section"><strong>Ambitious workflows:</strong> ${formatMarkdown(escapeHtml(synthesis.at_a_glance?.ambitious_workflows || ""))}</div>',
    '          </div>',
    '        </div>',
    '',
    '        <nav class="nav-toc">',
    '          <a href="#section-work">Work Areas</a>',
    '          <a href="#section-usage">Usage Patterns</a>',
    '          <a href="#section-wins">Wins</a>',
    '          <a href="#section-friction">Friction</a>',
    '          <a href="#section-features">Features</a>',
    '          <a href="#section-horizon">Horizon</a>',
    '        </nav>',
    '',
    '        <div class="stats-row">',
    '          <div class="stat"><div class="stat-value">${(stats.totalMessages || 0).toLocaleString()}</div><div class="stat-label">Messages</div></div>',
    '          <div class="stat"><div class="stat-value">+${(stats.linesAdded || 0).toLocaleString()}/-${(stats.linesRemoved || 0).toLocaleString()}</div><div class="stat-label">Lines</div></div>',
    '          <div class="stat"><div class="stat-value">${stats.filesTouchedCount || 0}</div><div class="stat-label">Files</div></div>',
    '          <div class="stat"><div class="stat-value">${stats.activeDays || 0}</div><div class="stat-label">Days</div></div>',
    '        </div>',
    '',
    '        <h2 id="section-work">What You Work On</h2>',
    '        <div class="project-areas">',
    '          ${(synthesis.project_areas || []).map(area => `',
    '            <div class="project-area">',
    '              <div class="area-header">',
    '                <span class="area-name">${escapeHtml(area.name)}</span>',
    '                <span class="area-count">${area.session_count} sessions</span>',
    '              </div>',
    '              <div class="area-desc">${escapeHtml(area.description)}</div>',
    '            </div>',
    '          `).join("")}',
    '        </div>',
    '',
    '        <div class="charts-row">',
    '          <div class="chart-card">',
    '            <div class="chart-title">Top Tools Used</div>',
    '            ${renderBarChart(stats.tools, "#0891b2")}',
    '          </div>',
    '          <div class="chart-card">',
    '            <div class="chart-title">Languages</div>',
    '            ${renderBarChart(stats.languages, "#10b981")}',
    '          </div>',
    '        </div>',
    '',
    '        <h2 id="section-usage">How You Use Gemini CLI</h2>',
    '        <div class="narrative">',
    '          ${(synthesis.interaction_style?.narrative || "").split("\\n\\n").map(p => `<p>${formatMarkdown(escapeHtml(p))}</p>`).join("")}',
    '          <div class="key-insight"><strong>Key pattern:</strong> ${escapeHtml(synthesis.interaction_style?.key_pattern || "")}</div>',
    '        </div>',
    '',
    '        <div class="chart-card" style="margin: 24px 0;">',
    '          <div class="chart-title">',
    '            <span class="tooltip" data-tip="Measures the time elapsed between a Gemini response and your next message. This highlights your \'think time\' or how quickly you iterate on Gemini\'s output.">User Response Time Distribution</span>',
    '          </div>',
    '          ${renderResponseTimes(stats.userResponseTimesBins)}',
    '          <div style="font-size: 12px; color: #64748b; margin-top: 8px;">',
    '            Median: ${(stats.median_response_time || 0).toFixed(1)}s &bull; Average: ${(stats.avg_response_time || 0).toFixed(1)}s',
    '          </div>',
    '        </div>',
    '',
    '        <div class="chart-card" style="margin: 24px 0;">',
    '          <div class="chart-title">Parallel Sessions (Multi-Session Activity)</div>',
    '          <div style="display: flex; gap: 24px; margin: 12px 0;">',
    '            <div style="text-align: center;">',
    '              <div style="font-size: 24px; font-weight: 700; color: #7c3aed;">${stats.multi_clauding?.overlap_events || 0}</div>',
    '              <div style="font-size: 11px; color: #64748b; text-transform: uppercase;">Overlap Events</div>',
    '            </div>',
    '            <div style="text-align: center;">',
    '              <div style="font-size: 24px; font-weight: 700; color: #7c3aed;">${stats.multi_clauding?.sessions_involved || 0}</div>',
    '              <div style="font-size: 11px; color: #64748b; text-transform: uppercase;">Sessions Involved</div>',
    '            </div>',
    '            <div style="text-align: center;">',
    '              <div style="font-size: 24px; font-weight: 700; color: #7c3aed;">${stats.totalMessages > 0 ? Math.round(100 * (stats.multi_clauding?.user_messages_during || 0) / stats.totalMessages) : 0}%</div>',
    '              <div style="font-size: 11px; color: #64748b; text-transform: uppercase;">Of Messages</div>',
    '            </div>',
    '          </div>',
    '        </div>',
    '',
    '        <div class="charts-row">',
    '          <div class="chart-card">',
    '            <div class="chart-title" style="display: flex; align-items: center; gap: 12px;">',
    '              Messages by Time of Day',
    '              <select id="timezone-select" style="font-size: 12px; padding: 4px; border-radius: 4px;">',
    '                <option value="0">Local</option>',
    '                <option value="-8">PT (UTC-8)</option>',
    '                <option value="0">UTC</option>',
    '                <option value="1">CET (UTC+1)</option>',
    '                <option value="9">JST (UTC+9)</option>',
    '              </select>',
    '            </div>',
    '            <div id="hour-histogram"></div>',
    '          </div>',
    '          <div class="chart-card">',
    '            <div class="chart-title">Tool Errors Encountered</div>',
    '            ${renderBarChart(stats.toolErrors || {}, "#dc2626")}',
    '          </div>',
    '        </div>',
    '',
    '        <h2 id="section-wins">Impressive Things You Did</h2>',
    '        <div class="big-wins">',
    '          ${(synthesis.what_works?.impressive_workflows || []).map(win => `',
    '            <div class="big-win">',
    '              <div class="big-win-title">${escapeHtml(win.title)}</div>',
    '              <div class="big-win-desc">${escapeHtml(win.description)}</div>',
    '            </div>',
    '          `).join("")}',
    '        </div>',
    '',
    '        <div class="charts-row">',
    '          <div class="chart-card">',
    '            <div class="chart-title">Outcomes</div>',
    '            ${renderBarChart(stats.qualitative?.outcomes || {}, "#8b5cf6")}',
    '          </div>',
    '          <div class="chart-card">',
    '            <div class="chart-title">Success Drivers</div>',
    '            ${renderBarChart(stats.qualitative?.successTypes || {}, "#16a34a")}',
    '          </div>',
    '        </div>',
    '',
    '        <h2 id="section-friction">Where Things Go Wrong</h2>',
    '        <div class="friction-categories">',
    '          ${(synthesis.friction_analysis?.categories || []).map(cat => `',
    '            <div class="friction-category">',
    '              <div class="friction-title">${escapeHtml(cat.category)}</div>',
    '              <div class="friction-desc">${escapeHtml(cat.description)}</div>',
    '              <ul class="friction-examples">',
    '                ${(cat.examples || []).map(ex => `<li>${escapeHtml(ex)}</li>`).join("")}',
    '              </ul>',
    '            </div>',
    '          `).join("")}',
    '        </div>',
    '',
    '        <div class="charts-row">',
    '          <div class="chart-card">',
    '            <div class="chart-title">Primary Friction Types</div>',
    '            ${renderBarChart(stats.qualitative?.frictionTypes || {}, "#dc2626")}',
    '          </div>',
    '          <div class="chart-card">',
    '            <div class="chart-title">Inferred Satisfaction</div>',
    '            ${renderBarChart(stats.qualitative?.satisfaction || {}, "#eab308")}',
    '          </div>',
    '        </div>',
    '',
    '        <h2 id="section-features">Suggested GEMINI.md Additions</h2>',
    '        <div class="claude-md-section">',
    '          ${(synthesis.suggestions?.gemini_md_additions || []).map(add => `',
    '            <div class="claude-md-item">',
    '              <code class="cmd-code">${escapeHtml(add.addition)}</code>',
    '              <div class="cmd-why"><strong>Why:</strong> ${escapeHtml(add.why)}</div>',
    '              <button class="copy-btn" onclick="copyText(this.parentElement.querySelector(\'.cmd-code\').textContent, this)">Copy Addition</button>',
    '            </div>',
    '          `).join("")}',
    '        </div>',
    '',
    '        <h2 id="section-horizon">On the Horizon</h2>',
    '        <div class="horizon-section">',
    '          ${(synthesis.on_the_horizon?.opportunities || []).map(o => `',
    '            <div class="horizon-card">',
    '              <div class="horizon-title">${escapeHtml(o.title)}</div>',
    '              <div class="horizon-possible">${escapeHtml(o.whats_possible)}</div>',
    '              <code class="copyable-prompt">${escapeHtml(o.copyable_prompt)}</code>',
    '              <button class="copy-btn" onclick="copyText(this.parentElement.querySelector(\'.copyable-prompt\').textContent, this)">Copy Prompt</button>',
    '            </div>',
    '          `).join("")}',
    '        </div>',
    '',
    '        ${synthesis.fun_moment ? `',
    '          <div class="fun-ending">',
    '            <div class="fun-headline">"${escapeHtml(synthesis.fun_moment.headline)}"</div>',
    '            <div class="fun-detail">${escapeHtml(synthesis.fun_moment.detail)}</div>',
    '          </div>',
    '        ` : ""}',
    '',
    '        ${stats.meta ? `',
    '          <div class="meta-stats">',
    '            <span>Qualitatively analyzed ${stats.meta.qualitativeSessionsAnalyzed} sessions</span>',
    '            <span>Generation Time: ${(stats.meta.generationTimeMs / 1000).toFixed(1)}s</span>',
    '          </div>',
    '        ` : ""}',
    '      `;',
    '',
    '      const updateHours = (offset) => {',
    '        const adjusted = new Array(24).fill(0);',
    '        (stats.hourlyActivity || []).forEach((count, h) => {',
    '          adjusted[(h + parseInt(offset) + 24) % 24] = count;',
    '        });',
    '        const bins = { ',
    '          "Morning (6-12)": adjusted.slice(6, 12).reduce((a, b) => a + b, 0),',
    '          "Afternoon (12-18)": adjusted.slice(12, 18).reduce((a, b) => a + b, 0),',
    '          "Evening (18-24)": adjusted.slice(18, 24).reduce((a, b) => a + b, 0),',
    '          "Night (0-6)": adjusted.slice(0, 6).reduce((a, b) => a + b, 0)',
    '        };',
    '        document.getElementById("hour-histogram").innerHTML = renderBarChart(bins, "#8b5cf6");',
    '      };',
    '      ',
    '      document.getElementById("timezone-select").addEventListener("change", (e) => updateHours(e.target.value));',
    '      updateHours(0);',
    '      ',
    '      document.getElementById("loader").style.display = "none";',
    '      root.style.display = "block";',
    '    }',
    '',
    '    window.addEventListener("load", renderApp);',
    '  </script>',
    '</body>',
    '</html>'
  ].join('\n');

  fs.writeFileSync(outputPath, htmlParts);
}

if (require.main === module) {
  const stats = JSON.parse(fs.readFileSync(process.argv[2], 'utf8'));
  const synthesis = JSON.parse(fs.readFileSync(process.argv[3], 'utf8'));
  generate(stats, synthesis, process.argv[4]);
}
